#!/bin/bash

projdir="/home/project/code/BlasterClient"
config="${projdir}/config.json"

if [ ! -f $config ]; then
    echo "File '$config' not found"
    exit 1
fi

while true
do
   echo "Running blasterclient"
    python "${projdir}/BlasterClient.py" "$config"
done

if [ $? -ne 0 ]; then
    echo "Error: BlasterClient.py crashed"
    exit 1
fi
